### ISSUE TITLE
[Feature Request] Support for searching Chinese names using Pinyin

### ISSUE THREAD

**Issue by Adlyq** [p-connor/plasma-drawer#66]
**Is your feature request related to a problem? Please describe.**
Hi I'm a Chinese user (zh_CN) and I can't search the app using Pinyin.
For example, firefox in Chinese characters is 火狐 and its pinyin is huohu.
I'm sure there must be a Chinese characters 2 Pinyin project on github

**Describe the solution you'd like**
Convert Chinese to Pinyin, then search like an English.

**Describe alternatives you've considered**
I used to manually rename the name to English, but there are many Chinese apps that default to Chinese characters, it's too much of a hassle

**Additional context**
like windwos...

**Comment by p-connor** [comment]
Hi, thanks for the suggestion! This is a good idea, however it should be implemented upstream. Plasma Drawer uses KRunner for search, so If KRunner supports Pinyin, then Plasma Drawer and all other system search will too. Please request this feature from KDE team so that it’s available across the system and for every user.

If for some reason what you’re asking for works in KRunner, but does not work in Plasma Drawer, please re-open this issue. Thanks!
